---

- name: "Tasks for all machines"
  hosts: all
  gather_facts: yes
  vars:
    package_install: [
      { add_item: 'curl' },
      { add_item: 'wget' },
      { add_item: 'lsof' },
      { add_item: 'dos2unix' },
      { add_item: 'tmux' },
      { add_item: 'vim' },
      { add_item: 'git' },
      { add_item: 'make' },
      { add_item: 'net-tools' },
      { add_item: 'tcpdump' },
      { add_item: 'socat' },
      { add_item: 'expect' },
      { add_item: 'sshfs' },
      { add_item: 'acl' },
      { add_item: 'ca-certificates' },
      { add_item: 'python3-virtualenv' },
      { add_item: 'python3-pip' }
    ]
    package_remove: [
      { del_item: 'telnet' }
    ]
    create_folders: [
      { dir: '/opt/data/', mode: '0775', owner: 'root', group: 'vagrant' },
      { dir: '/root/tmp/', mode: '0700', owner: 'root', group: 'root' },
      { dir: '/opt/cluster/', mode: '0700', owner: 'root', group: 'root' }
    ]
  tasks:
    - name: "checks and debug"
      block:
        - name: "OS check"
          assert:
            that:
              - ansible_architecture in ['x86_64', 'arm64']
        - name: Display hostname
          debug:
            msg: "inventory_hostname {{ inventory_hostname }}"
    - name: "system config"
      block:
        - name: "files and folders"
          block:
            - name: "create common folders"
              ansible.builtin.file:
                path: "{{ item.dir }}"
                state: directory
                mode: "{{ item.mode }}"
                owner: "{{ item.owner }}"
                group: "{{ item.group }}"
              with_items: "{{ create_folders }}"
      become: true
    - name: "install software"
      block:
        - name: "install OS packages"
          ansible.builtin.package:
            name: "{{ item.add_item }}"
            state: present
          retries: 3
          with_items: "{{ package_install }}"
          become: true
          tags:
            - software
        - name: "remove OS packages"
          ansible.builtin.package:
            name: "{{ item.del_item }}"
            state: absent
          with_items: "{{ package_remove }}"
          become: true
          tags:
            - software
    - name: "Finish up"
      block:
        - name: "create readme"
          ansible.builtin.copy:
            dest: /home/vagrant/readme.txt
            mode: 0644
            content: |
              # --- VM details ---
              #  distro:      {{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_architecture }}
              #  ansible:     {{ ansible_version }}
              #  python:      {{ ansible_playbook_python }}
              #  vm_comment:  {{ vm_comment }}
        - name: "debug note"
          debug:
            msg: "tasks for all hosts finished"


- name: "Ansible controller tasks"
  hosts: ansiblebox
  vars:
    create_folders_ansible: [
      { dir: '/home/vagrant/code/', mode: '0775', owner: 'vagrant', group: 'vagrant' },
      { dir: '/home/vagrant/fetched/', mode: '0775', owner: 'vagrant', group: 'vagrant' }
    ]
  tasks:
    - name: "system config"
      block:
        - name: "files and folders"
          block:
            - name: "create common folders"
              ansible.builtin.file:
                path: "{{ item.dir }}"
                state: directory
                mode: "{{ item.mode }}"
                owner: "{{ item.owner }}"
                group: "{{ item.group }}"
              with_items: "{{ create_folders_ansible }}"
      become: true


- name: "Tasks worker node"
  hosts: compute
  tasks:
    - name: "Finish up"
      block:
        - name: "create worker readme"
          ansible.builtin.copy:
            dest: /home/vagrant/worker.txt
            mode: 0644
            content: |
              # worker machine
        - name: "debug note"
          debug:
            msg: "tasks for all hosts finished"
