---


- name: "Tasks for all machines"
  hosts: all
  gather_facts: yes
  vars:
    package_install: [
      { add_item: 'curl' },
      { add_item: 'wget' },
      { add_item: 'lsof' },
      { add_item: 'dos2unix' },
      { add_item: 'tmux' },
      { add_item: 'vim' },
      { add_item: 'git' },
      { add_item: 'make' },
      { add_item: 'net-tools' },
      { add_item: 'tcpdump' },
      { add_item: 'socat' },
      { add_item: 'expect' },
      { add_item: 'sshfs' },
      { add_item: 'acl' },
      { add_item: 'python3-virtualenv' },
      { add_item: 'python3-pip' }
    ]
    package_remove: [
      { del_item: 'telnet' }
    ]
    create_folders: [
      { dir: '/etc/ansible/facts.d/', mode: '0755', owner: 'root', group: 'root' },
      { dir: '/opt/data/', mode: '0775', owner: 'root', group: 'vagrant' },
      { dir: '/root/tmp/', mode: '0700', owner: 'root', group: 'root' },
      { dir: '/mnt/sshfs/', mode: '0775', owner: 'root', group: 'root' }
    ]
  tasks:
    - name: "checks and debug"
      block:
        - name: "OS check"
          assert:
            that:
              - ansible_os_family == "Debian"
              - ansible_architecture in ['x86_64', 'arm64']
        - name: Display hostname
          debug:
            msg: "inventory_hostname {{ inventory_hostname }}"
    - name: "system config"
      block:
        - name: "files and folders"
          block:
            - name: "create common folders"
              ansible.builtin.file:
                path: "{{ item.dir }}"
                state: directory
                mode: "{{ item.mode }}"
                owner: "{{ item.owner }}"
                group: "{{ item.group }}"
              with_items: "{{ create_folders }}"
      become: true
    - name: "install software"
      block:
        - name: "install OS packages"
          ansible.builtin.package:
            name: "{{ item.add_item }}"
            state: present
          retries: 3
          with_items: "{{ package_install }}"
          become: true
          tags:
            - software
        - name: "remove OS packages"
          ansible.builtin.package:
            name: "{{ item.del_item }}"
            state: absent
          with_items: "{{ package_remove }}"
          become: true
          tags:
            - software
    - name: "Finish up"
      block:
        - name: "script to run ansible"
          ansible.builtin.copy:
            dest: /home/vagrant/run-playbook.sh
            mode: 0755
            content: |
              echo "running playbook.yml on localhost";
              if [[ root = "$(whoami)" ]]; then
                echo "Error: do not run as root";
                exit 1;
              fi
              export ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3
              ansible-playbook -v --connection=local -i "127.0.0.1," -- /vagrant/playbook.yml;
        - name: "create readme"
          ansible.builtin.copy:
            dest: /home/vagrant/readme.txt
            mode: 0644
            content: |
              # --- Dev VM details ---
              # distro:   {{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_architecture }}
              # ansible:  {{ ansible_version }}
              # python:   {{ ansible_playbook_python }}
        - name: "debug note"
          debug:
            msg: "tasks for all hosts finished"


- name: "other vm"
  hosts: "ubnt2004*"
  tasks:
    - name: "user account"
      block:
        - name: "create account"
          ansible.builtin.user:
            name: compute
            shell: /bin/bash
        - name: "add ssh key"
          ansible.posix.authorized_key:
            user: compute
            state: present
            key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5aUbU0enzDnT8AS6XhEr1QrfyEYgccC1u+yeL0VlkRsRKCrc2ZExLSyhgzlovo5EFGF9SqBpVi6q6UXxwJp2KDJ+9tHLhmlMYj2TPsb3MYCrjR4vJdvEfwK7bUhS4UMN+apRVoSsUNUczOqB8dpzVScVA7rMlJIJ0GK10EJvVEVcwGlfY1KgAsX+k0mtUzRNBFZlB+2XDj7awqLweMbVkbZvbNWeRzwcLH6YP0JGSen9NfOwyWkASTaXcY8Ze4L+I4ECeQwiJvumK95AaojMg+z/7VsnFd+GX3rxlORCr+wHyL5W+qPoNXERx75SpykMk7tHioH27RKX+rL2Zgok9b9fAK7I8NC9b8ENL/omOV+0tG1FpEEr8aNPVrE/+j8SzIS36Gqq5WFGP/MjScOE0RIOUK39nmW3QR8H1f6wt9eUSYjxqrY5crkYUYsU1KmiABrYfhYdq3MNthbRieOyD5kUGxmAnFsO98dUT8fodtnHc0EfSxEesl1/rFXOBZxE= user.local"
      become: true
    - name: "debug note"
      debug:
        msg: "tasks for ubnt2004* finished"