---
collections:
  - name: https://github.com/ansible-collections/community.general
    type: git
    version: 4.6.1
  - name: https://github.com/dev-sec/ansible-collection-hardening
    type: git
    version: 7.14.1
